### ISSUE TITLE
`spotinst-sdk` should install its dependencies

### ISSUE THREAD

**Issue by vkhromov** [spotinst/spotinst-sdk-python#6]
`spotinst-sdk` 1.0.29 doesn't install its dependencies automatically:
```
$ virtualenv venv
New python executable in venv/bin/python
Installing setuptools, pip, wheel...done.

$ . ./venv/bin/activate

(venv)$ pip install spotinst-sdk==1.0.29
Collecting spotinst-sdk==1.0.29
/tmp/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/b6/14/2cd3a2f3e21fab34f7e3089c51873f1d396f89105108abd46a215b342fa2/spotinst-sdk-1.0.29.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-kZ9LLj/spotinst-sdk/setup.py", line 7, in <module>
        import spotinst_sdk
      File "spotinst_sdk/__init__.py", line 5, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kZ9LLj/spotinst-sdk
```

It works only after a manual installation of `requests` and `PyYAML`:
```
$ pip install requests
Collecting requests
/tmp/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: urllib3, idna, certifi, chardet, requests
Successfully installed certifi-2018.4.16 chardet-3.0.4 idna-2.7 requests-2.19.1 urllib3-1.23

$ pip install pyyaml
Collecting pyyaml
/tmp/venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached https://files.pythonhosted.org/packages/4a/85/db5a2df477072b2902b0eb892feb37d88ac635d36245a72a6a69b23b383a/PyYAML-3.2.tar.gz
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml
  Stored in directory: /tmp/.cache/pip/wheels/03/05/65/bdc14f2c6e09e82ae3e0f13d021e1b6b2481437ea2f207df3f
Successfully built pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-3.12

$ pip install spotinst-sdk==1.0.29
Collecting spotinst-sdk==1.0.29
  Using cached https://files.pythonhosted.org/packages/b6/14/2cd3a2f3e21fab34f7e3089c51873f1d396f89105108abd46a215b342fa2/spotinst-sdk-1.0.29.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in ./venv/lib/python2.7/site-packages (from spotinst-sdk==1.0.29)
Requirement already satisfied (use --upgrade to upgrade): PyYaml in ./venv/lib/python2.7/site-packages (from spotinst-sdk==1.0.29)
Requirement already satisfied (use --upgrade to upgrade): urllib3<1.24,>=1.21.1 in ./venv/lib/python2.7/site-packages (from requests->spotinst-sdk==1.0.29)
Requirement already satisfied (use --upgrade to upgrade): idna<2.8,>=2.5 in ./venv/lib/python2.7/site-packages (from requests->spotinst-sdk==1.0.29)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in ./venv/lib/python2.7/site-packages (from requests->spotinst-sdk==1.0.29)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in ./venv/lib/python2.7/site-packages (from requests->spotinst-sdk==1.0.29)
Building wheels for collected packages: spotinst-sdk
  Running setup.py bdist_wheel for spotinst-sdk
  Stored in directory: /tmp/.cache/pip/wheels/14/ff/60/03492054d0f1609a497c197053ee9e3c3dfba663fb930e102c
Successfully built spotinst-sdk
Installing collected packages: spotinst-sdk
Successfully installed spotinst-sdk-1.0.29
```

**Comment by danieldop** [comment]
Hey @vkhromov, thank you for raising our awareness concerning this issue, we've deployed a fix which solves the matter.
